services:
  mysql:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: upcycleconnect
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 5s
      timeout: 5s
      retries: 10

  api:
    build: ./api
    restart: on-failure
    ports:
      - "8080:8080"
    environment:
      DB_DSN: root:root@tcp(mysql:3306)/upcycleconnect?parseTime=true&charset=utf8mb4
      JWT_SECRET: a33346c14310829ba428ec9630d436de1c842633a47fffb1e84c20ea8196a16e
      SMTP_HOST: smtp.office365.com
      SMTP_PORT: 587
      SMTP_USER: upcycleconnect.notif@outlook.com
      SMTP_PASS: ET45Z-2AY9F-GHG3G-47V59-AALGG
      APP_URL: http://145.241.169.248
    depends_on:
      mysql:
        condition: service_healthy

  frontend:
    build: ./frontend
    restart: unless-stopped
    ports:
      - "80:80"
    environment:
      API_BASE_URL: http://api:8080/api
    depends_on:
      - api

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - "8081:8080"
    depends_on:
      - mysql

volumes:
  mysql_data: