
SET @s := IF((SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='Planning_personnel' AND COLUMN_NAME='Titre')=0,
    "ALTER TABLE Planning_personnel ADD COLUMN Titre VARCHAR(150) NOT NULL DEFAULT ''",'DO 0');
PREPARE st FROM @s; EXECUTE st; DEALLOCATE PREPARE st;
SET @s := IF((SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='Planning_personnel' AND COLUMN_NAME='Lieu')=0,
    "ALTER TABLE Planning_personnel ADD COLUMN Lieu VARCHAR(150) NULL",'DO 0');
PREPARE st FROM @s; EXECUTE st; DEALLOCATE PREPARE st;
SET @s := IF((SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='Planning_personnel' AND COLUMN_NAME='Description')=0,
    "ALTER TABLE Planning_personnel ADD COLUMN Description VARCHAR(255) NULL",'DO 0');
PREPARE st FROM @s; EXECUTE st; DEALLOCATE PREPARE st;
